### ISSUE TITLE
意外终止了连接。

### ISSUE THREAD

**Issue by bAnonym** [onplus/shadowsocks-heroku#1]
设置确认无误，错误提示如图
![tim 20171007122623](https://user-images.githubusercontent.com/5017696/31304733-51d03e1e-ab5b-11e7-845d-b347bf4ff14a.png)

**Comment by onplus** [comment]
https://github.com/mrluanma/shadowsocks-heroku/issues/3

改成 `"remote_port": 80, ` 试试

https://github.com/onplus/shadowsocks-heroku/blob/223fe6305fb9c896206d0f0f0759446930148515/config.json#L1-L10

**Comment by bAnonym** [comment]
可以了！感谢！

**Comment by bAnonym** [comment]
大佬有可能封装一个mac能用的吗
nexe。。。看不懂

**Comment by onplus** [comment]
我在win7下打包的，虚拟机的黑苹果崩了 没测试 。

```
 nexe local.js  --target  mac-x64-6.9.5 
```

 [mac-x64-6.9.5.zip](https://github.com/onplus/shadowsocks-heroku/files/1364580/mac-x64-6.9.5.zip)

**Comment by bAnonym** [comment]
不知道哪里有问题，不过还是谢谢了！
![wx20171007-233323](https://user-images.githubusercontent.com/5017696/31309379-fc1e88ce-abb7-11e7-8611-7981459a1f54.png)

**Comment by onplus** [comment]
把config.json 复制到/users/b_anonym/  下试试？

**Comment by bAnonym** [comment]
试过了，就会这样
![wx20171008-001433](https://user-images.githubusercontent.com/5017696/31309740-c8d2d438-abbd-11e7-97e9-5cb7e0670c76.png)

**Comment by onplus** [comment]
json格式不对，英文双引号

**Comment by bAnonym** [comment]
确实有两个引号是全角的！改过来后复制到用户根目录就可以用了！虽然不知道为什么，编译的时候引号会自己变全角吗。。。

{
  "server": "XXX.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": 1080,
  "remote_port": 80,
  "password": "password",
  "timeout": 600,
  "method": "aes-256-cfb"
}

这样就是对的
我觉得可以放到release里了。

**Comment by huaxiangniaoyu** [comment]
运行ss-h-taskbar-r.exe后，显示address in use, aborting然后闪退了，没法用，地址使用中是什么意思？搭建已经成功，json也已经正确修改了。
