### ISSUE TITLE
这个页面被墙https://id.heroku.com

### ISSUE THREAD

**Issue by muyufan** [onplus/shadowsocks-heroku#10]
我以前有注册过heroku好像，但是现在登录不了，晕死

**Comment by onplus** [comment]
提供临时账号，一小时后我改密码
```
{
  "server": "onplus.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "1080",
  "remote_port": "80",
  "password": "onplus",
  "timeout": 600,
  "method": "aes-256-cfb"
}
```

**Comment by muyufan** [comment]
好 我试试

**Comment by onplus** [comment]
部署好了吗？我去改密码啦。
一个小时有十几个ip访问了这个账号。。。

**Comment by sakuratyan** [comment]
同求

**Comment by onplus** [comment]
@sakuratyan  十一点前有效
{
  "server": "onplus.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "1080",
  "remote_port": "80",
  "password": "shadowsocks",
  "timeout": 600,
  "method": "aes-256-cfb"
}

**Comment by sakuratyan** [comment]
address in use, aborting

**Comment by onplus** [comment]
1080端口和xtunnel冲突，你可以改成 "local_port": "8888",

**Comment by HeminWon** [comment]
注册时一直提示 Please confirm you're not a robot. 无法进入登录页

**Comment by onplus** [comment]
@HeminWon  https://github.com/onplus/shadowsocks-heroku/issues/10#issuecomment-335328334 临时用一下

**Comment by sakuratyan** [comment]
@onplus 

server listening at { address: '127.0.0.1', family: 'IPv4', port: 8888 }

还是打不开Google   和 https://id.heroku.com/

**Comment by onplus** [comment]
@sakuratyan switchyomega也要改对应端口

**Comment by sakuratyan** [comment]
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }   重启，端口改回来了

**Comment by sakuratyan** [comment]
![image](https://user-images.githubusercontent.com/21052933/31366419-5a586c4c-ada3-11e7-9381-9374f25b5c29.png)
b @onplus

**Comment by onplus** [comment]
你没用一键部署吗？
服务端只需要自定义两个
![qeqw](https://user-images.githubusercontent.com/31188782/31366506-ecd18892-ada3-11e7-9e29-bf673c21ddcf.JPG)

**Comment by sakuratyan** [comment]
没找到自动部署 @onplus

**Comment by onplus** [comment]
就是那个紫色的图标
https://github.com/onplus/shadowsocks-heroku#部署

**Comment by sakuratyan** [comment]
![image](https://user-images.githubusercontent.com/21052933/31366577-5769ed0c-ada4-11e7-90b5-cbf3ed7b925e.png)

**Comment by sakuratyan** [comment]
就是  那个页面的   尴尬

**Comment by badabiba** [comment]
onplus 客户端无法启动

**Comment by onplus** [comment]
@badabiba 可能是端口冲突，修改local_port。或者关掉 xxnet/ss

**Comment by galaxyunion** [comment]
@onplus
求个临时帐号
id.heroku.com完全上不去，已注册

**Comment by onplus** [comment]
@galaxyunion https://github.com/onplus/shadowsocks-heroku/issues/14

**Comment by galaxyunion** [comment]
@onplus 非常感谢
