### ISSUE TITLE
启动客户端后闪退

### ISSUE THREAD

**Issue by YunXuyun** [onplus/shadowsocks-heroku#109]
无论我双击ss-h.exe还是start.vbs，都不行。
是不是我少安装了什么软件所以才会这样？

**Comment by onplus** [comment]
https://sourceforge.net/projects/shadowsocks-heroku/files/win-taskbar/

**Comment by YunXuyun** [comment]
嗯对是这个原因，刚才把ssr关了又重启电脑，现在可以用了。
谢谢解答！～

**Comment by caofengzi** [comment]
端口衝突，關閉其中軟件一個即可，不變重啟計算機。
