### ISSUE TITLE
使用方法怪异，不知道怎么设置。

### ISSUE THREAD

**Issue by styrenes** [onplus/shadowsocks-heroku#127]
按方法都设置好了服务器。
但是手机用shadowsocks客户端连不上。
没有给出地址，用户名，秘密等

**Comment by onplus** [comment]
这个版本不能用在SS客户端上

![image](https://user-images.githubusercontent.com/31188782/34440589-075b13cc-ecf1-11e7-888a-1c7f592a463f.png)

**Comment by styrenes** [comment]
这个v2ray更麻烦，一个连接接着一个连接，连服务器都设置不了。
就不能写一个例子说明一下设置，借鉴一下。
谁会一开始就了解一切呢。

**Comment by onplus** [comment]
要么花钱要么花时间
