### ISSUE TITLE
本地代理不响应，求解

### ISSUE THREAD

**Issue by bymanaire** [onplus/shadowsocks-heroku#13]
![1](https://user-images.githubusercontent.com/2795737/31346553-0d8779dc-ad4c-11e7-8fb8-41c9a4a01c83.png)

配置文件

```
{
  "server": 
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "8082",
  "remote_port": "80",
  "password": 
  "timeout": 600,
  "method": "aes-256-cfb"
}
```

**Comment by onplus** [comment]
https://github.com/onplus/shadowsocks-heroku/issues/12#issuecomment-335195587

**Comment by bymanaire** [comment]
@onplus 我用你的服务器并改成1080端口还是一样的情况

浏览器直接访问服务器可行，显示
```
https://github.com/onplus/shadowsocks-heroku
```

**Comment by onplus** [comment]
把日志截全了，只暴露地址没问题的

**Comment by bymanaire** [comment]
@onplus 


![1](https://user-images.githubusercontent.com/2795737/31366574-53e62b8c-ada4-11e7-9c4e-85f534f92e6c.png)

**Comment by onplus** [comment]
switchyomega 怎么配置的？

**Comment by bymanaire** [comment]
![image](https://user-images.githubusercontent.com/2795737/31366895-3d49a384-ada6-11e7-9fc7-47227a0ae63d.png)
![image](https://user-images.githubusercontent.com/2795737/31366907-4d46ffe8-ada6-11e7-83d2-ba20a92c5a74.png)

**Comment by bymanaire** [comment]
@onplus 什么也没改，问题复现
本地连接无限超时，这次重启网卡也没用了= =|||

![default](https://user-images.githubusercontent.com/2795737/31585482-e77646d0-b1f4-11e7-9405-886dc7022e5d.png)


![2](https://user-images.githubusercontent.com/2795737/31585492-05bcf846-b1f5-11e7-9cd7-0ab275553820.png)

**Comment by onplus** [comment]
有没有firefox浏览器？

**Comment by gggccc44** [comment]
@onplus 

我也一直连不上，访问网站火狐提示您的连接不安全，ie提示此网站的安全证书存在问题

强行访问就404，哪里没对？

**Comment by onplus** [comment]
@gggccc44 
有问题请单独提issue，贴图贴日志

**Comment by gggccc44** [comment]
@onplus 
嗯嗯

貌似解决了，我用火狐在pan里面设置为远程dns就好了，然后其他浏览器啥都没改也行了，估计是dns污染

**Comment by eightHundreds** [comment]
@onplus 想了解一下,为啥浏览器还需要代理插件
传统的shadowsocks却不需要?
是否有可能通过打开一个应用让全局翻墙
