### ISSUE TITLE
临时账号 更新

### ISSUE THREAD

**Issue by onplus** [onplus/shadowsocks-heroku#14]
## 更新于12月29日14:21

临时使用账号，会不定时改password和method 。

仅帮助新手进行第一次的注册部署，滥用者IP将会被记录
[](123.161.111.98)[](222.89.14.98)

账号一（python版）
```
{
  "server": ["wsss.herokuapp.com"],
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "1080",
  "remote_port": "80",
  "password": "H8Wa6^TH98",
  "timeout": 600,
  "method": "aes-256-cfb"
}
```

**Comment by wangippy** [comment]
@onplus 这个是有流量限制么？

**Comment by onplus** [comment]
@wangippy https://github.com/onplus/shadowsocks-heroku/issues/4#issuecomment-335014663

**Comment by ablebodied** [comment]
多谢大神的临时账号，搞了两个小时，终于成功，感谢

**Comment by rarest** [comment]
你好这个账号怎么用

**Comment by onplus** [comment]
@rarest 覆盖config.json内容，点击taskbar.exe运行

**Comment by rarest** [comment]
@onplus 多谢啦，正在配自己的账号

**Comment by briteming** [comment]
兄弟这个版本搞得不错啊，比https://github.com/mrluanma/shadowsocks-heroku 和 https://github.com/521xueweihan/shadowsocks-heroku/tree/master 方便很多。谢谢你！

**Comment by jiangcm** [comment]
用了你提供的最新的账号也翻不了，是不是我路由器哪里被设置了？（规则是从你的备份导入的）

**Comment by c6132a1** [comment]
qwe

**Comment by TaoChingChung** [comment]
可以用ShadowSocks使用这个服务器吗？ 如果可以 端口那些 该填多少啊？
