### ISSUE TITLE
没找到deploy to heroku按钮

### ISSUE THREAD

**Issue by robinwar** [onplus/shadowsocks-heroku#16]
汗,只有创建新app,里面只有名字和线路选项,没有算法和密码设定
然后按照教程来就不成功,试用临时账户可用,求教

**Comment by HeminWon** [comment]
同问

**Comment by tislam8888** [comment]
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fonplus%2Fshadowsocks-heroku&template=https%3A%2F%2Fgithub.com%2Fonplus%2Fshadowsocks-heroku%2Ftree%2Fre

**Comment by onplus** [comment]
。。。
可能我教程写的有点模糊，就是这个页面的紫色按钮 https://github.com/onplus/shadowsocks-heroku#部署

点击后会访问
https://heroku.com/deploy?template=https://github.com/onplus/shadowsocks-heroku/tree/re

**Comment by robinwar** [comment]
搞定了,多谢

**Comment by HeminWon** [comment]
@onplus  如何查看自己是否已经部署了呢？https://dashboard.heroku.com/ 这里没有找到已经部署的app
