### ISSUE TITLE
部署账号了，然后上不去

### ISSUE THREAD

**Issue by tommyclerk** [onplus/shadowsocks-heroku#17]
试了下临时账号，可以上，好神奇，就密码不一样，加密方法和网址都一样。部署按照教程1.2都做了，也注册了app name。但是连接出现这个connecting twitter.com via ws://onplus.herokuapp.com:80/
remote disconnected

**Comment by sakuratyan** [comment]
这还是临时账号ya

**Comment by tommyclerk** [comment]
我自己注册了个，也按照教程部署了，就上不去，拿临时测试了下可以

**Comment by sakuratyan** [comment]
截个图啊

**Comment by onplus** [comment]
你的网址不会和我一样的，appname在heroku是唯一的

**Comment by sakuratyan** [comment]
@onplus   苹果手机  怎么办   wingy  用过吗

**Comment by tommyclerk** [comment]
图片上传错误，请问网址是哪个，教程没写出哈，app name注册了

**Comment by sakuratyan** [comment]
https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Fonplus%2Fshadowsocks-heroku&template=https%3A%2F%2Fgithub.com%2Fonplus%2Fshadowsocks-heroku%2Ftree%2Fre

**Comment by onplus** [comment]
这张图里
![](https://user-images.githubusercontent.com/31188782/31343896-ab0a868a-ad43-11e7-8a83-369cf5e385b0.jpg)

**Comment by tommyclerk** [comment]
就是速度好卡，和xx tunnel一样， 我这twitter等刷不出图片，youtube也是打不开视频、、。

**Comment by tislam8888** [comment]
@tommyclerk 
我这里用起来很快
能看youtube的1080P

**Comment by HeminWon** [comment]
报 response <200>
