### ISSUE TITLE
多建一个APP的问题

### ISSUE THREAD

**Issue by kendyho** [onplus/shadowsocks-heroku#18]
首先感谢项目负责人，为大家免费提供了一个优秀的fq平台！

我依照文档提示建了一个app，fq成功，想再建立一个，使用欧洲服。但第二次建立的时候，选项好像没第一次多，也没让我输入密码，选择加密方式什么的。结果第二个连接失败，请问应该如何设置，谢谢！

**Comment by onplus** [comment]
一键部署 https://heroku.com/deploy?template=https://github.com/onplus/shadowsocks-heroku/tree/re

 自定义配置部署，你需要fork本项目，然后参考
https://github.com/521xueweihan/shadowsocks-heroku/tree/master#二部署

**Comment by kendyho** [comment]
感谢回复，已成功，一键部署太强大！ @onplus
