### ISSUE TITLE
你们用的速度怎么样  我的这个速度太慢了看youtube几乎不可能

### ISSUE THREAD

**Issue by njsurfing** [onplus/shadowsocks-heroku#27]
![new ba l4d 6q4xjn 7 a](https://user-images.githubusercontent.com/24504639/31378144-e3220d60-addc-11e7-9fab-d461f8ca532a.png)

**Comment by wangippy** [comment]
我这里看无压力，下载youtube的也差不多800KB/S

**Comment by njsurfing** [comment]
那就怪了  我用其它SS都能看高清的

**Comment by njsurfing** [comment]
那是怎么回事  用其它SS都能看高清的

**Comment by wangippy** [comment]
你用的美国还是欧洲的？

**Comment by njsurfing** [comment]
美国的

**Comment by lhyGit** [comment]
我用的美国的 速度很快啊。。。。

**Comment by tislam8888** [comment]
@wangippy 
你是用什么下载工具下载的？

**Comment by tislam8888** [comment]
我这里很快 可以看1080P 无压力

**Comment by yelldan** [comment]
我这里速度也可以

**Comment by c6132a1** [comment]
有时快，有时慢
