### ISSUE TITLE
到底怎么注册谁来帮帮我

### ISSUE THREAD

**Issue by wangfeng769** [onplus/shadowsocks-heroku#35]
![image](https://user-images.githubusercontent.com/10465093/31474781-9066984e-af2f-11e7-92b6-cd1d629e56ab.png)
要不要带后面的“.herokuapp.com”带上名字不可用，不带又出现错误

**Comment by onplus** [comment]
就是这个app name “wangfeng”已经被占用了，取个其他的“wangfeng171012”

**Comment by wangfeng769** [comment]
@onplus 能不能加下你qq帮我看下，或者你加下我10518590，验证：王锋

**Comment by wangfeng769** [comment]
@onplus 
![image](https://user-images.githubusercontent.com/10465093/31475373-199403e2-af33-11e7-855b-bc4c178f69d8.png)我的网站登陆上去是这样，部署已经完成了
![image](https://user-images.githubusercontent.com/10465093/31475399-3fba8c12-af33-11e7-8913-6383f76b7fb5.png)
后台打开是这样，外网显示无法打开网页

**Comment by onplus** [comment]
重新部署一次
https://heroku.com/deploy?template=https://github.com/onplus/shadowsocks-heroku/tree/re

**Comment by wangfeng769** [comment]
@onplus 还是不行，能不能加下我帮我看看，这个说话起来很不方便
