### ISSUE TITLE
求助，部署界面到底怎么操作，一直弄不好

### ISSUE THREAD

**Issue by wangfeng769** [onplus/shadowsocks-heroku#36]
![image](https://user-images.githubusercontent.com/10465093/31476121-629718f0-af37-11e7-89a6-4f1f10028894.png)
现在还成了这，怎么删除或者怎么重新弄，谁能远程帮我看下，或者有详细的部署教程

**Comment by tislam8888** [comment]
不用那么复杂

**Comment by wangfeng769** [comment]
@tislam8888 能不能远程教教我

**Comment by tislam8888** [comment]
部署的是时候 不用填那个ID
他自己会生成个name

**Comment by wangfeng769** [comment]
@tislam8888 到底怎么弄，我的一直报错呀，远程下可以吗，一早上了，快疯了

**Comment by onplus** [comment]
你已经部署了五个app了！
