### ISSUE TITLE
谢谢onplus 的耐心指导，已经没问题了

### ISSUE THREAD

**Issue by wangfeng769** [onplus/shadowsocks-heroku#38]
部署老出错，累

**Comment by onplus** [comment]
请把你已经部署的五个APP删除 再部署新的

**Comment by wangfeng769** [comment]
@onplus 怎么删除我都找不到，哎

**Comment by onplus** [comment]
你会英语吗？会用谷歌翻译也行

**Comment by wangfeng769** [comment]
已经删了一个，还是不知道怎么部署

**Comment by onplus** [comment]
一步一步做，点击这个
https://heroku.com/deploy?template=https://github.com/onplus/shadowsocks-heroku/tree/re

**Comment by wangfeng769** [comment]
@onplus 然后呢，刚开始就是这么弄得

**Comment by onplus** [comment]
截图呢

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477088-9da374de-af3c-11e7-8928-8b94805d8d38.png)

**Comment by onplus** [comment]
点deploy ，  等待编译
，截图

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477130-db0a83bc-af3c-11e7-8afc-9b7b643aa1d1.png)

**Comment by onplus** [comment]
点view

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477156-f3c2513c-af3c-11e7-8526-7cf897b3aa59.png)

**Comment by wangfeng769** [comment]
@onplus 这是好了吗

**Comment by onplus** [comment]
部署正确。
config.json贴一下，密码用xxx代替

**Comment by wangfeng769** [comment]
我试试

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477209-4535d138-af3d-11e7-9ed6-64029ef159c7.png)

![image](https://user-images.githubusercontent.com/10465093/31477241-7ef8518e-af3d-11e7-85b0-4cadbf2cea1d.png)
@onplus 还是这

**Comment by onplus** [comment]
switchyomega 配置贴一下

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477272-ac3f1ff6-af3d-11e7-92ee-4fcc3404b48b.png)

**Comment by tislam8888** [comment]
端口是1080 才对

**Comment by onplus** [comment]
你刚刚部署的appname是什么？确定是wangfeng.herokuapp.com ?

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477330-f7b11a48-af3d-11e7-9edc-0c32c0918691.png)
我总感觉是这错了，端口1080会跟xx-net冲突，所以改成8089了

**Comment by wangfeng769** [comment]
确定是wangfeng.herokuapp.com @onplus

**Comment by onplus** [comment]
你第一张截图里可不是

**Comment by onplus** [comment]
我给的免费账号能连上吗？

**Comment by wangfeng769** [comment]
部署的时候改了，我重新部署个给你截图

**Comment by wangfeng769** [comment]
@onplus 免费号可以上

**Comment by wangfeng769** [comment]
![image](https://user-images.githubusercontent.com/10465093/31477427-9872e7b8-af3e-11e7-8294-d18d14abdc2d.png)
@onplus 箭头处要不要选

**Comment by onplus** [comment]
不选

**Comment by wangfeng769** [comment]
那是哪不对了
