### ISSUE TITLE
有个问题想问一下onplus

### ISSUE THREAD

**Issue by samtone** [onplus/shadowsocks-heroku#4]
非常感谢你的教程 gae ip 都被封完了 通过你这个又能上yt了 就想问一下通过这个heroku免费的服务是有流量限制或者什么其他限制吗？？ 
另外能简单教一下 你最后提到的cow/meow怎么设置吗 我看了一下那边的说明 有点看不懂欸。。。

**Comment by onplus** [comment]
有运行时间和运行数量的一些限制，没看到流量限制
https://devcenter.heroku.com/articles/limits
https://dashboard.heroku.com/account/billing 

不能访问谷歌学术 #3

了解一下就行，不要折腾，项目已经停止更新了。
cow是一个智能代理软件，自动检测网站是否被墙，仅对被墙网站使用二级代理。
我推荐是因为某些应用不能使用socks5，cow可以把socks5转成http，还可以提供给局域网的手机使用
参考配置rc.txt  https://github.com/cyfdecyf/cow/blob/master/doc/sample-config/rc
```
# cow提供局域网代理
listen = http://0.0.0.0:8089
allowedClient = 127.0.0.1, 192.168.1.0/24, 10.0.0.0/8

#多个二级代理
proxy = socks5://127.0.0.1:10801
proxy = http://127.0.0.1:8087
proxy = http://user:password@127.0.0.1:8080
```
Windows双击 cow-taskbar.exe，隐藏到托盘执行，
然后设置 其他软件/手机 的代理 192.168.1.xxx:8089

**Comment by ylg1024** [comment]
@onplus 非常感谢你简化操作  我XP系统 无法运行这个软件 
This application is only supported on Windows 7, Windows Server 2008 R2, or high
er     能否编译个XP版本的 谢谢

**Comment by onplus** [comment]
@ylg1024 
试试新打包的ss-h-win32 https://github.com/onplus/shadowsocks-heroku/releases/tag/Node.js-4.8.4
估计是之前选的nodejs 6.2.2 不支持XP，换成4.8.8应该可以了

**Comment by ylg1024** [comment]
@onplus 搞定 速度还不错 谢谢
