### ISSUE TITLE
python版本部署出错--谢谢

### ISSUE THREAD

**Issue by ylg1024** [onplus/shadowsocks-heroku#44]
Error response

Error code: 405

Message: Method Not Allowed.

Error code explanation: 405 - Specified method is invalid for this resource.

**Comment by onplus** [comment]
浏览器直接访问server，返回这个信息说明部署正确了

**Comment by ylg1024** [comment]
确实 @onplus  哈哈

**Comment by onplus** [comment]
我稍微修改了一下，现在网页访问可以查看静态页面，示例：https://ss-ws-py.herokuapp.com/
你先fork项目[shadowsocks-websocket-python](https://github.com/onplus/shadowsocks-websocket-python)，修改webdir文件夹的index.html，甚至可以放几张html做一个小的静态网站。
然后在已经部署好的app里重新部署，注意是deploy分支，不是master分支
![image](https://user-images.githubusercontent.com/31188782/31599590-98afad2a-b285-11e7-8524-bb12e79ef485.png)
连接到自己fork的项目
![image](https://user-images.githubusercontent.com/31188782/31599622-b3e8b15e-b285-11e7-8e5b-bcd0d8981401.png)
### 注意是deploy分支，不是master分支
![image](https://user-images.githubusercontent.com/31188782/31599628-bca446f0-b285-11e7-8a36-7599c5ef374a.png)
