### ISSUE TITLE
如果我部署了两个项目，配置文件应该如何配置呢？

### ISSUE THREAD

**Issue by andytree** [onplus/shadowsocks-heroku#48]
我能想到的是：
第一是把程序文件复制两份，相对隔离。如果要用哪个，那么就运行哪个。我部署一个美国，一个欧洲的。
第二是配置写到一个config.json中，程序自动两个都走，还是其他策略？
> config.json
```
{
  "server": "xx2.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "1080",
  "remote_port": "80",
  "password": "xx",
  "timeout": 600,
  "method": "aes-256-cfb"
}
{
  "server": "xx1.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": "1080",
  "remote_port": "80",
  "password": "xx",
  "timeout": 600,
  "method": "aes-256-cfb"
}
```
请问下，现在程序支持第二种吗？

**Comment by onplus** [comment]
https://github.com/onplus/shadowsocks-heroku/issues/34#issuecomment-335843455

会js的话可以修改[源码](https://github.com/onplus/shadowsocks-heroku/tree/re/src)，优化多server处理
https://github.com/onplus/shadowsocks-heroku/blob/f2d67249232f5becc35f0237ca5673466a0fbc67/local.js#L97-L109

或者 #47

**Comment by tislam8888** [comment]
我基本上只用一个 美国的很快了
欧洲服 不咋地

**Comment by andytree** [comment]
onplus给的链接里面有使用方式，我再贴一下[#34 (comment)](https://github.com/onplus/shadowsocks-heroku/issues/34#issuecomment-335843455)
