### ISSUE TITLE
请问，SwitchyOmega按照方法配置，ss-h启动成功，仍然无法浏览YouTube

### ISSUE THREAD

**Issue by liyibo123** [onplus/shadowsocks-heroku#5]
该怎么解决呢？？？

**Comment by onplus** [comment]
贴一下日志

**Comment by liyibo123** [comment]
![2017-10-09_182743](https://user-images.githubusercontent.com/31808137/31334365-9fc571ae-ad20-11e7-8e54-8d7e5a903645.jpg)

**Comment by onplus** [comment]
"remote_port": 80 , 不是 8080
https://github.com/onplus/shadowsocks-heroku/blob/re/config.json

**Comment by liyibo123** [comment]
@onplus 谢谢你啊，用你的方法解决了

**Comment by tislam8888** [comment]
server  那里应该填什么

**Comment by onplus** [comment]
@tislam8888 就是  "你的appname.herokuapp.com"

**Comment by tislam8888** [comment]
@onplus 
感谢
