### ISSUE TITLE
如何自动使用多个heroku app？

### ISSUE THREAD

**Issue by suoba** [onplus/shadowsocks-heroku#60]
由于每一个heroku的app流量很少，看几个视频就没了，能否设置自动使用多个app呢？几个512M加起来就够用了

**Comment by onplus** [comment]
heroku不限流量，只限时长，一个月一个账号550个小时。

https://github.com/onplus/shadowsocks-heroku/issues/34#issuecomment-335843455
```
{
  "server": ["ss1.herokuapp.com","ss2.herokuapp.com"],
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": 1080,
  "remote_port": 80,
  "password": "sspassword",
  "timeout": 600,
  "method": "aes-256-cfb"
}
```

**Comment by caofengzi** [comment]
每個月有550小時免費使用一個帳號足以，哪個人能夠每天使用18小時的基本沒有，還要謝謝開發者的無私奉獻，更加悲哀的是，想瀏覽真正的互聯網還需要準備各種姿勢。

**Comment by suoba** [comment]
哦，明白了。谢谢
