### ISSUE TITLE
部署貌似成功了，但mac命令行打开失败

### ISSUE THREAD

**Issue by rarest** [onplus/shadowsocks-heroku#62]
以下时部署log
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_VERBOSE=false
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version 6.x...
       Downloading and installing node 6.11.4...
       Using default npm version: 3.10.10
-----> Restoring cache
       Skipping cache restore (not-found)
-----> Building dependencies
       Installing node modules (package.json)
       shadowsocks-heroku@0.9.10 /tmp/build_17889c3e7677739190ad1f056074b014/onplus-shadowsocks-heroku-f2d6724
       ├─┬ https-proxy-agent@1.0.0
       │ ├─┬ agent-base@2.1.1
       │ │ └── semver@5.0.3
       │ ├─┬ debug@2.6.9
       │ │ └── ms@2.0.0
       │ └── extend@3.0.1
       ├── minimist@1.2.0
       └─┬ ws@1.1.4
       ├── options@0.0.6
       └── ultron@1.0.2
       
-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)
-----> Build succeeded!
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 13.6M
-----> Launching...
       Released v4
       https://rarest.herokuapp.com/ deployed to Heroku

mac上 ./ss-h的时候出错了

undefined:2
  "server": “rarest.herokuapp.com",
            ^

SyntaxError: Unexpected token “
    at Object.parse (native)
    at Number.<anonymous> (/Users/csq/Tools/ss-h-mac/ss-h:51:17)
    at Number.<anonymous> (/Users/csq/Tools/ss-h-mac/ss-h:326:4)
    at c (/Users/csq/Tools/ss-h-mac/ss-h:7221:3281)
    at Function.r.import (/Users/csq/Tools/ss-h-mac/ss-h:7221:3747)
    at /Users/csq/Tools/ss-h-mac/ss-h:7218:15
    at Object.<anonymous> (/Users/csq/Tools/ss-h-mac/ss-h:7221:1)
    at Module._compile (module.js:409:26)
    at _third_party_main.js:45:20
    at NativeModule.compile (node.js:1031:7)

**Comment by onplus** [comment]
https://github.com/onplus/shadowsocks-heroku/issues/43#issuecomment-337466588

**Comment by rarest** [comment]
@onplus 可以了，多谢了！ mac上犯这种错误几次了，json文件格式容易错误， 还不长记性
