### ISSUE TITLE
未越狱的ios上这个可以用吗

### ISSUE THREAD

**Issue by hatplay** [onplus/shadowsocks-heroku#74]
未越狱的ios上这个可以用吗？比如用shadowrocket配置一下能用吗？我试了一下，不知道是自己配置不对还是本身就不能用。

**Comment by onplus** [comment]
这不能直接用在 SS/SSR客户端


折衷方法 https://github.com/onplus/shadowsocks-heroku/issues/47

**Comment by hatplay** [comment]
好的，谢谢！

**Comment by HeminWon** [comment]
@onplus  mac 链接WIFI的电脑不能用这个么？

**Comment by onplus** [comment]
@HeminWon 没明白你的描述。
无论无线还是有线都能用
