### ISSUE TITLE
ss-h 在Ubuntu上面可以使用吗

### ISSUE THREAD

**Issue by Sloancc** [onplus/shadowsocks-heroku#8]

**Comment by onplus** [comment]
我是觉得用linux的可能更喜欢自己运行node，就没打包。
https://github.com/onplus/shadowsocks-heroku/blob/master/README.md

**Comment by Sloancc** [comment]
按照教程配置之后还是无法上网。
config.jeson如下（在http://www.bejson.com/校验了，没问题）：
{
  "server": "sloancc.herokuapp.com",
  "local_address": "127.0.0.1",
  "scheme": "ws",
  "local_port": 1080,
  "remote_port": 80,
  "password": "sloancc",
  "timeout": 600,
  "method": "aes-256-cfb"
}
server,password,method填写无误。

SwitchyOmega也已经配置为了：SOCKS5，127.0.0.1，1080

运行local.js后显示：
http proxy: http://127.0.0.1:34359/
server listening at { address: '127.0.0.1', family: 'IPv4', port: 1080 }
local connected
concurrent connections: 1
remote clients1.google.com:443 error: Error: connect ECONNREFUSED 127.0.0.1:34359
remote disconnected
concurrent connections: 0
local connected
concurrent connections: 1
remote clients1.google.com:443 error: Error: connect ECONNREFUSED 127.0.0.1:34359
remote disconnected
concurrent connections: 0
local connected
concurrent connections: 1
remote clients1.google.com:443 error: Error: connect ECONNREFUSED 127.0.0.1:34359
remote disconnected
concurrent connections: 0
local connected
concurrent connections: 1
remote clients1.google.com:443 error: Error: connect ECONNREFUSED 127.0.0.1:34359
remote disconnected
。。。。。。

**Comment by Sloancc** [comment]
这个地址和我用的lantern中的地址一样
HTTP(S) proxy: 127.0.0.1:34359
SOCKS proxy: 127.0.0.1:34347，难道是lantern的原因吗

**Comment by onplus** [comment]
"local_port": 1080 换成其他端口看看

**Comment by Sloancc** [comment]
还是不行：
http proxy: http://127.0.0.1:34359/
server listening at { address: '127.0.0.1', family: 'IPv4', port: 8080 }
local connected
concurrent connections: 1
local connected
concurrent connections: 2
local connected
concurrent connections: 3
local connected
concurrent connections: 4
local connected
concurrent connections: 5
local connected
concurrent connections: 6
local connected
concurrent connections: 7
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 6
local connected
concurrent connections: 7
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 6
local connected
concurrent connections: 7
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
local connected
concurrent connections: 6
local connected
concurrent connections: 7
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
local connected
concurrent connections: 6
local connected
concurrent connections: 7
remote www.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
local connected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
local connected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 4
local connected
concurrent connections: 5
local connected
concurrent connections: 6
remote clients1.google.com:443 error: Error: read ECONNRESET
remote disconnected
concurrent connections: 5
remote clients1.google.com:443 error: Error: read ECONNRESET

**Comment by onplus** [comment]
你是不是设置了蓝灯全局代理？

**Comment by onplus** [comment]
测试了一下，你的服务端部署成功了。
![qwe](https://user-images.githubusercontent.com/31188782/31337950-1413c7f4-ad30-11e7-8335-599999277cb6.JPG)

你把地址和密码贴出来会被盗用的。。

**Comment by Sloancc** [comment]
没有设置全局代理，
只是选中了manage system proxy
没有选中proxy all traffic
而且试过了，不启动蓝灯以及取消选中manage system proxy 还是均无法上网

**Comment by onplus** [comment]
启动后不应该出现这个`http proxy: http://127.0.0.1:34359/`
试试
```
unset http_proxy
node local.js
```

**Comment by Sloancc** [comment]
unset http_proxy 之后问题解决了，非常感谢
