### ISSUE TITLE
求助，连接失败

### ISSUE THREAD

**Issue by EmmieMcDonald** [onplus/shadowsocks-heroku#9]
![default](https://user-images.githubusercontent.com/14090545/31333196-ac9d3efc-ad1b-11e7-8c79-3431996fa743.png)

**Comment by onplus** [comment]
。。。你没改config.json server和password

**Comment by EmmieMcDonald** [comment]
@onplus 
password 改了，server 不知道怎么改

**Comment by onplus** [comment]
你的server呢

**Comment by EmmieMcDonald** [comment]
成功了，谢谢，原来要到 build log 里找到 server 修改

**Comment by onplus** [comment]
不是啊，修改config.json就可以了
```
{
"server": "XXX.herokuapp.com",
"local_address": "127.0.0.1",
"scheme": "ws",
"local_port": 1080,
"remote_port": 80,
"password": "password",
"timeout": 600,
"method": "aes-256-cfb"
}
```

**Comment by EmmieMcDonald** [comment]
是的，有两处需要修改，看部署说明时没看明白．自己看着文件内容只修改了密码和端口（默认与X-tunnel冲突）

{
"server": "此处需修改为个人app名字.herokuapp.com",
"local_address": "127.0.0.1",
"scheme": "ws",
"local_port": 1080,
"remote_port": 80,
"password": "此处修改为个人app密码",
"timeout": 600,
"method": "aes-256-cfb"
}
