### ISSUE TITLE
heroku不能用，我就配置cow，不管怎么配置SwitchyOmega，就是不成功

### ISSUE THREAD

**Issue by JMaxime** [onplus/shadowsocks-heroku#96]
SwitchyOmega选项怎么配置呢，@onplus 大大求助

**Comment by JMaxime** [comment]
求助！！！

**Comment by onplus** [comment]
heroku 官方服务出现问题

**Comment by sundaqing1969** [comment]
![7fa92467jw1dvf0gic5ypj](https://user-images.githubusercontent.com/13601611/32228818-4103c870-be8a-11e7-95df-cc4a2e6d262f.jpg)

**Comment by sundaqing1969** [comment]
shadowsocks-heroku只能被谷歌浏览器使用？@onplus

**Comment by JMaxime** [comment]
@sundaqing1969 我用的是QQ浏览器

**Comment by sundaqing1969** [comment]
@JMaxime，QQ浏览器代理怎么设置的？我火狐不行，安全证书通不过

**Comment by sundaqing1969** [comment]
![05fddf9d-dfeb-4f05-acd4-c42f8b2676a9](https://user-images.githubusercontent.com/13601611/32323553-5b16170c-c003-11e7-8775-7c6c913137b1.jpg)

**Comment by JMaxime** [comment]
@sundaqing1969 #56
