### ISSUE TITLE
老板请指教

### ISSUE THREAD

**Issue by mkjn00** [onplus/shadowsocks-heroku#99]
我有一架linux的机器也想用这个梯子，卡在npm install这一步不知道怎么过，求教。已经下载了你那个linux-x86文件，不知道怎么用。。
代码显示这样
root@kali:/home/linux# npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/linux/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/linux/package.json'
npm WARN linux No description
npm WARN linux No repository field.
npm WARN linux No README data
npm WARN linux No license field.

up to date in 1.076s
root@kali:/home/linux#

**Comment by onplus** [comment]
下载了可执行文件，就不用装nodejs了，直接运行 ./ss-h

**Comment by mkjn00** [comment]
你的意思是直接用windows的客户端在linux运行？

**Comment by onplus** [comment]
你已经装了nodejs？
参考这个吧
https://github.com/mrluanma/shadowsocks-heroku

**Comment by mkjn00** [comment]
已经装了，就是卡在npm install那里
不知道怎么继续，google了半天也没找到方法。。

**Comment by mkjn00** [comment]
linux-x86-6.11.0  这个文件不知道要怎么用，请指示。。

**Comment by onplus** [comment]
1. 下载解压https://github.com/onplus/shadowsocks-heroku/archive/re.zip
2. 文件夹下打开终端，运行`npm install`
3. 编辑config.json，运行`node local.js -c config.json`

**Comment by onplus** [comment]
终端运行 ./linux-x86-6.11.0

**Comment by mkjn00** [comment]
解决了，谢谢老板，吃饭去了。。
